### ISSUE TITLE
Error de transferencia(Opción 5-Ordenar Transferencia)

### ISSUE THREAD

**Issue by 779799** [779799/Sistemas-Legados-21-22#4]
Tras confirmar la realización de una transferencia lleva a pantalla de error.

**Comment by RusudoDev** [comment]
Error reproducido: sólo ocurre cuando la cuenta destino de la transferencia no tiene ninguna entrada en el fichero de movimientos.

Posible solución: eliminar comprobación INVALID KEY de la lectura F-MOVIMIENTOS de la cuenta destino.
